openapi: 3.0.0
info:
  title: PR Compass API
  version: 1.0.0
paths:
  /title-recommend:
    get:
      summary: Get title recommendations
      responses:
        '200':
          description: A list of recommended titles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecommendResponse'
  /judge:
    post:
      summary: Judge a title
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: The result of judging the title
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JudgeResult'
  /similar:
    post:
      summary: Find similar titles
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: A list of similar titles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SimilarResponse'
components:
  schemas:
    RecommendResponse:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
    JudgeResult:
      type: object
      properties:
        result1:
          type: boolean
        result2:
          type: boolean
        result3:
          type: boolean
    SimilarResponse:
      type: object
      properties:
        corporationName:
          type: string
        publishdDatetime:
          type: string
        thumbnailUrl:
          type: string
        postUrl:
          type: string
        title:
          type: string
        like_count:
          type: integer